/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_xtapi_serviceProvider_MSTAPI */

#ifndef _Included_net_xtapi_serviceProvider_MSTAPI
#define _Included_net_xtapi_serviceProvider_MSTAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_xtapi_serviceProvider_MSTAPI
 * Method:    initTapi
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_xtapi_serviceProvider_MSTAPI_initTapi
  (JNIEnv *, jobject);

/*
 * Class:     net_xtapi_serviceProvider_MSTAPI
 * Method:    openLine
 * Signature: (ILjava/lang/StringBuffer;)I
 */
JNIEXPORT jint JNICALL Java_net_xtapi_serviceProvider_MSTAPI_openLine
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     net_xtapi_serviceProvider_MSTAPI
 * Method:    connectCall
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_net_xtapi_serviceProvider_MSTAPI_connectCall
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     net_xtapi_serviceProvider_MSTAPI
 * Method:    answerCall
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_xtapi_serviceProvider_MSTAPI_answerCall
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_xtapi_serviceProvider_MSTAPI
 * Method:    dropCall
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_xtapi_serviceProvider_MSTAPI_dropCall
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_xtapi_serviceProvider_MSTAPI
 * Method:    getCallInfo
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_net_xtapi_serviceProvider_MSTAPI_getCallInfo
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_xtapi_serviceProvider_MSTAPI
 * Method:    shutDown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_xtapi_serviceProvider_MSTAPI_shutDown
  (JNIEnv *, jobject);

/*
 * Class:     net_xtapi_serviceProvider_MSTAPI
 * Method:    monitorDigits
 * Signature: (IZ)I
 */
JNIEXPORT jint JNICALL Java_net_xtapi_serviceProvider_MSTAPI_monitorDigits
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     net_xtapi_serviceProvider_MSTAPI
 * Method:    sendDigits
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_xtapi_serviceProvider_MSTAPI_sendDigits
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     net_xtapi_serviceProvider_MSTAPI
 * Method:    playSound
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_net_xtapi_serviceProvider_MSTAPI_playSound
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     net_xtapi_serviceProvider_MSTAPI
 * Method:    recordSound
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_net_xtapi_serviceProvider_MSTAPI_recordSound
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     net_xtapi_serviceProvider_MSTAPI
 * Method:    stopRecording
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_xtapi_serviceProvider_MSTAPI_stopRecording
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_xtapi_serviceProvider_MSTAPI
 * Method:    stopPlaying
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_xtapi_serviceProvider_MSTAPI_stopPlaying
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
